---
- name: Install FreeIPA server
  ansible.builtin.package:
    name:
      - freeipa-healthcheck
      - freeipa-server

- name: Copy DHS CA certs
  ansible.builtin.get_url:
    dest: /usr/local/share
    mode: 0600
    url: https://pki.treas.gov/dhsca_fullpath.p7b
- name: Convert P7B to PEM
  ansible.builtin.command:
    cmd: >
      openssl pkcs7 -print_certs
      -in /usr/local/share/dhsca_fullpath.p7b
      -inform DER
      -out /usr/local/share/dhsca_fullpath.pem
    creates: /usr/local/share/dhsca_fullpath.pem

- name: Copy setup script
  ansible.builtin.copy:
    dest: /usr/local/sbin
    mode: 0500
    src: 00_setup_freeipa.sh

- name: Configure FreeIPA and install a cron job to disable inactive users
  when:
    - freeipa_disable_inactive_users
  block:
    - name: Copy inactive user setup script
      ansible.builtin.copy:
        dest: /usr/local/sbin
        mode: 0500
        src: 01_setup_disabling_of_inactive_users.sh
    - name: Install a daily cron job to disable inactive users
      ansible.builtin.copy:
        dest: /etc/cron.daily
        mode: 0500
        src: disable_inactive_users.sh

- name: Install Apache config fragment to disable trace functionality
  ansible.builtin.copy:
    dest: /etc/httpd/conf.d
    mode: 0500
    src: disable_trace.conf
  when:
    - freeipa_disable_trace

- name: Install Apache config fragment to enable HSTS functionality
  ansible.builtin.copy:
    dest: /etc/httpd/conf.d
    mode: 0500
    src: enable_hsts.conf
  when:
    - freeipa_enable_hsts
