---
- name: Install FreeIPA server
  ansible.builtin.package:
    name:
      - freeipa-healthcheck
      - freeipa-server

- name: Install a daily cron job to disable inactive users
  ansible.builtin.template:
    src: disable_inactive_users.j2.sh
    dest: /etc/cron.daily/disable_inactive_users.sh
    mode: 0500

- name: Copy DHS CA certs
  ansible.builtin.get_url:
    dest: /usr/local/share
    mode: 0600
    url: https://pki.treas.gov/dhsca_fullpath.p7b
- name: Convert P7B to PEM
  ansible.builtin.command:
    cmd: >
      openssl pkcs7 -print_certs
      -in /usr/local/share/dhsca_fullpath.p7b
      -inform DER
      -out /usr/local/share/dhsca_fullpath.pem
    creates: /usr/local/share/dhsca_fullpath.pem

- name: Copy setup script
  ansible.builtin.copy:
    src: 00_setup_freeipa.sh
    dest: /usr/local/sbin
    mode: 0500
