---
# This molecule configuration file is suitable for testing Ansible
# roles that _do not_ require SystemD.  If your Ansible role _does_
# require SystemD then you should use molecule-with-systemd.yml
# instead.
#
# Note that the molecule configuration file that is symlinked to
# molecule.yml is the one that will be used.
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  # FreeIPA server is only available for the RedHat, Fedora, and
  # CentOS Linux distributions.  Among these distributions we only
  # support Fedora.
  - image: fedora:37
    name: fedora37
    platform: amd64
  - image: fedora:38
    name: fedora38
    platform: amd64
scenario:
  name: default
verifier:
  name: testinfra
